export type MapLegend = Record<string, string>;

export const mapLegend: MapLegend = {
  '=': 'road',
  '┌': 'stone_wall_corner_tl',
  '┐': 'stone_wall_corner_tr',
  '┘': 'stone_wall_corner_br',
  '└': 'stone_wall_corner_bl',
  '|': 'stone_wall_straight_v',
  '#': 'stone_wall_straight_h',
  '1': 'iron_fence_corner_tl',
  '2': 'iron_fence_corner_tr',
  '3': 'iron_fence_corner_br',
  '4': 'iron_fence_corner_bl',
  'v': 'iron_fence_straight_v',
  'h': 'iron_fence_straight_h',
  'S': 'crypt',
  'B': 'bench',
  'L': 'lantern_candle',
  'T': 'pine',
  't': 'pine_crooked',
  'O': 'oak',
  '+': 'gravestone_cross',
  'o': 'gravestone_round',
  '-': 'gravestone_broken',
  '.': 'void',
}

export const level1 = [
  '┌-------------------------┐',
  '|T..o..h..T..===..T..h..o.|',
  '|..+...h.....===.....h...+T',
  '|T...-.h..S..===..S..h.-..|',
  '|..T...h.....===.....h...T|',
  '|.+..┌-------===-------┐.+|',
  '|....+.......===.......+..|',
  '|T.o...T..t..===..t..T...o|',
  '|...-.....B..===..B.....-.|',
  '|.T...hhhh...===...hhhh...|',
  '|..+.h....T..=+=..T....h.+|',
  '|o..h........===........h.|',
  '|T.h...o..T..===..T..o...h|',
  '|.h...-......===......-...h',
  '|T....T...t..===..t...T...|',
  '|..+.....o...===...o.....+|',
  '|o....S......===......S..o|',
  '|T..t.....T..===..T.....t.|',
  '└-------------------------┘',
] as const;
